easyfuse-pipeline:
  image: continuumio/miniconda3:23.5.2-0
  stage: build
  script:
    - conda install -c bioconda nextflow=24.10.1
    - bash test/scripts/test_00.sh
    - bash test/scripts/test_fusionannotation.sh
