repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - LICENSE
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-easyfuse_logo_light.png
    - docs/images/nf-core-easyfuse_logo_light.png
    - docs/images/nf-core-easyfuse_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
    - ro-crate-metadata.json
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-easyfuse_logo_light.png
    - docs/images/nf-core-easyfuse_logo_light.png
    - docs/images/nf-core-easyfuse_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/email_template.html
    - assets/slackreport.json
    - assets/adaptivecard.json
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CITATIONS.md

template:
  org: TRON
  name: EasyFuse
  description: EasyFuse is a pipeline to detect fusion transcripts from paired-end
    RNA-seq data with high accuracy.
  author: xyz
  version: 2.2.0
  force: true
  outdir: .
  skip_features:
    - license
    - fastqc
    - seqera_platform
    - citations
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
